export const GET_COMMENTS = 'GET_COMMENTS';
export const GET_A_COMMENT = 'GET_A_COMMENT';
export const ADD_COMMENT = 'ADD_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const COMMENTS_LOADING = 'COMMENTS_LOADING';

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const LOGIN_GOOGLE_SUCCESS = "LOGIN_GOOGLE_SUCCESS";
export const USER_DELETE_ACCOUNT = "USER_DELETE_ACCOUNT";
export const USER_UPDATE_ACCOUNT = "USER_UPDATE_ACCOUNT";

export const GET_DONATION_ADS = "GET_DONATION_ADS";
export const GET_DONATION_AD = "GET_DONATION_AD";
export const ADD_DONATION_AD = "ADD_DONATION_AD";
export const DELETE_DONATION_AD = "DELETE_DONATION_AD";
export const UPDATE_DONATION_AD = "UPDATE_DONATION_AD";

export const GET_KEEPER_ADS = "GET_KEEPER_ADS";
export const GET_KEEPER_AD = "GET_KEEPER_AD";
export const ADD_KEEPER_AD = "ADD_KEEPER_AD";
export const DELETE_KEEPER_AD = "DELETE_KEEPER_AD";
export const UPDATE_KEEPER_AD = "UPDATE_KEEPER_AD";